run:
  timeout: 5m

linters:
  enable:
    - misspell
    - goconst
    - unconvert
    - prealloc
    - nilerr
    - unparam
    - wastedassign
    - makezero
    - bodyclose
    - errorlint
  disable:
    - gocyclo
    - dupl
    - gosec
    - exhaustive

linters-settings:
  gocyclo:
    min-complexity: 40
  dupl:
    threshold: 150
  goconst:
    min-len: 3
    min-occurrences: 3
  misspell:
    locale: US
    ignore-words:
      - basecamp
      - github
