# .goreleaser.yml
# GoReleaser configuration for bc4

# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
version: 2
project_name: bc4

before:
  hooks:
    # You may remove this if you don't use go modules
    - go mod tidy
    # Run tests before building
    - go test ./...

builds:
  - id: bc4
    main: ./main.go
    binary: bc4
    
    # Custom ldflags for version injection
    ldflags:
      - -s -w
      - -X github.com/needmore/bc4/internal/version.Version={{.Version}}
      - -X github.com/needmore/bc4/internal/version.GitCommit={{.Commit}}
      - -X github.com/needmore/bc4/internal/version.BuildDate={{.Date}}
    
    # Build for macOS, Linux, and Windows
    goos:
      - darwin
      - linux
      - windows
    
    # Build for Intel (amd64) and ARM (arm64)
    goarch:
      - amd64
      - arm64
    
    # Ignore combinations that don't make sense
    ignore:
      - goos: windows
        goarch: arm64
    
    # Environment variables
    env:
      - CGO_ENABLED=0
    
    # Build mode
    mod_timestamp: '{{ .CommitTimestamp }}'

# Create universal binary for macOS
universal_binaries:
  - id: bc4-universal
    ids:
      - bc4
    replace: true
    name_template: "bc4"

archives:
  - id: bc4-archive
    builds:
      - bc4
      - bc4-universal
    
    # Archive name template
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    
    # Use tar.gz for Unix systems, zip for Windows
    format_overrides:
      - goos: windows
        format: zip
    
    # Additional files to include
    files:
      - LICENSE*
      - README.md

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'
      - '^build:'
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
  groups:
    - title: 'New Features'
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug Fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: 'Performance Improvements'
      regexp: "^.*perf[(\\w)]*:+.*$"
      order: 2
    - title: 'Code Refactoring'
      regexp: "^.*refactor[(\\w)]*:+.*$"
      order: 3
    - title: 'Other Changes'
      order: 999

release:
  # GitHub release settings
  github:
    owner: needmore
    name: bc4
  
  # Release name template
  name_template: "{{.ProjectName}} v{{.Version}}"
  
  # Disable auto-publishing (can be overridden with --release-notes)
  draft: false
  
  # Add release notes
  footer: |
    ## Installation
    
    ### Homebrew (macOS - Recommended)
    ```bash
    brew install needmore/bc4/bc4
    ```
    
    ### Direct Download
    Download the appropriate archive for your system from the assets below.
    
    #### macOS
    - Intel Macs: `bc4_*_Darwin_x86_64.tar.gz`
    - Apple Silicon Macs: `bc4_*_Darwin_arm64.tar.gz`
    
    Extract and install:
    ```bash
    tar -xzf bc4_*.tar.gz
    sudo mv bc4 /usr/local/bin/
    ```
    
    #### Linux
    - Intel/AMD 64-bit: `bc4_*_Linux_x86_64.tar.gz`
    - ARM 64-bit: `bc4_*_Linux_arm64.tar.gz`
    
    Extract and install:
    ```bash
    tar -xzf bc4_*.tar.gz
    sudo mv bc4 /usr/local/bin/
    ```
    
    #### Windows
    - 64-bit: `bc4_*_Windows_x86_64.zip`
    
    Extract the zip file and add `bc4.exe` to your PATH.

# Homebrew tap configuration (same repository)
brews:
  - name: bc4
    repository:
      owner: needmore
      name: bc4
      branch: main
    directory: Formula
    homepage: "https://github.com/needmore/bc4"
    description: "A CLI tool for interacting with Basecamp 4"
    license: "MIT"

    # Commit author
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com

    # Commit message
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"

    # Skip upload if formula already exists
    skip_upload: auto