# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bc4 < Formula
  desc "A CLI tool for interacting with Basecamp 4"
  homepage "https://github.com/needmore/bc4"
  version "0.1.0"
  license "MIT"
  depends_on :macos

  url "https://github.com/needmore/bc4/releases/download/v0.1.0/bc4_0.1.0_Darwin_all.tar.gz"
  sha256 "33f5df53e2aea31aaa9154067685a0daef6aaa60e61cfac86f9fd046cf3a51d2"

  def install
    bin.install "bc4"
  end
end
