# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bc4 < Formula
  desc "A CLI tool for interacting with Basecamp 4"
  homepage "https://github.com/needmore/bc4"
  version "0.12.0"
  license "MIT"

  on_macos do
    url "https://github.com/needmore/bc4/releases/download/v0.12.0/bc4_0.12.0_Darwin_all.tar.gz"
    sha256 "cccf3b5a686cd076259f1405d07e722a473c800374ffce0318671deb17f139e2"

    def install
      bin.install "bc4"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/needmore/bc4/releases/download/v0.12.0/bc4_0.12.0_Linux_x86_64.tar.gz"
      sha256 "1f29509a94c8f693ad5e3ffd26707df9a063e6c14e919515e4fff870243cd75d"
      def install
        bin.install "bc4"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/needmore/bc4/releases/download/v0.12.0/bc4_0.12.0_Linux_arm64.tar.gz"
      sha256 "1f492f2fea07f616fe82e6b52d28d8abd7fcd474e30b9fbb892da7a277d51eea"
      def install
        bin.install "bc4"
      end
    end
  end
end
